### PR TITLE
Add PyPI trove classifiers for Python 3

### LINKED ISSUE #53: Add Python 3 trove classifiers to setup.py
To help assist tools like https://caniusepython3.com/ it would be useful to add Python 3 trove classifiers to setup.py, eg:
```
Programming Language :: Python :: 3
Programming Language :: Python :: 3.4
Programming Language :: Python :: 3.5
```

### PR DESCRIPTION
**Pull request by edmorley**
Fixes #53.

### CODE REVIEW

**Comment by GaretJax** [comment]
Thanks Ed, good catch. Before merging I wonder if I want to have Py 2.6 in there.
It might work, but don't want to support it explicitly.

**Comment by edmorley** [comment]
Hi! I used the version list from `.travis.yml` - I can either just drop it from this PR, or also remove it from the Travis run?

**Comment by GaretJax** [comment]
Let's do both then, thank you!

I'll try to get other issues fixed as well and a release uploaded to pypi

**Comment by edmorley** [comment]
Thank you for doing that in c5a984b6ca2bc56bf3f44e2e4542f1f0751769d8 :-)

**Pull request merged**
